var $jscomp={scope:{},global:this,initSymbolIterator:function(){Symbol=$jscomp.global.Symbol||{};Symbol.iterator||(Symbol.iterator="$jscomp$iterator");$jscomp.initSymbolIterator=function(){}},makeIterator:function(a){$jscomp.initSymbolIterator();if(a[Symbol.iterator])return a[Symbol.iterator]();if(!(a instanceof Array)&&"string"!=typeof a)throw Error();var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}},copyProperties:function(a,b){for(var c in b)a[c]=b[c]},inherits:function(a,
b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a}},enabled=!1,poolSetting,paramSetting,freqSet,voltSet,pools=[],avalons=[],jobQueue=[{thisId:-1,value:[]},{thisId:-1,value:[]},{thisId:-1,value:[]}],thread=new Worker("thread.js"),threadPaused=!1,workQueue={value:[],shift:function(){1E3>workQueue.value.length&&threadPaused&&(thread.postMessage({info:"resume"}),threadPaused=!1);return this.value.shift()},push:function(a){1023<=workQueue.value.length&&(thread.postMessage({info:"pause"}),
threadPaused=!0);return this.value.push(a)},init:function(){this.value=[]}},activePool=Infinity,hashrates=[],errors=[],totalHashrate=Array.apply(null,Array(721)).map(Number.prototype.valueOf,0);
chrome.app.runtime.onLaunched.addListener(function(){chrome.storage.local.get("pool",function(a){poolSetting=a.pool||[]});chrome.storage.local.get("param",function(a){paramSetting=a.param||[]});chrome.app.window.create("index.html",{innerBounds:{width:1E3,height:700,minWidth:1E3,minHeight:700},id:"Avalon miner"},function(){chrome.app.window.get("Avalon miner").onClosed.addListener(function(){var a;enable=!1;for(a=0;a<avalons.length;a++)void 0!==avalons[a]&&(avalons[a].stop(),delete avalons[a]);for(a=
0;a<pools.length;a++)void 0!==pools[a]&&(pools[a].disconnect(),delete pools[a]);thread.postMessage({info:"stop"});chrome.runtime.onMessage.removeListener(messageHandler);chrome.hid.onDeviceAdded.removeListener(hidAddedHandler);chrome.hid.onDeviceRemoved.removeListener(hidRemovedHandler);chrome.sockets.tcp.onReceive.removeListener(tcpHandler);chrome.sockets.tcp.onReceiveError.removeListener(tcpErrorHandler);close()})});chrome.runtime.onMessage.addListener(messageHandler)});
var messageHandler=function(a,b){var c;if(-1!==b.url.indexOf("index.html"))switch(a.type){case "ready":prelude();break;case "start":main();break;case "enableLog":utils.enableLog();break;case "disableLog":utils.disableLog();break;case "setting":if(void 0!==a.pool){for(c=0;c<pools.length;c++)pools[c].disconnect(),delete pools[c];poolSetting=a.pool;if(enabled)for(thread.postMessage({info:"clean"}),activePool=Infinity,c=0;c<poolSetting.length;c++){var d=poolSetting[c];pools[c]=new Pool(c,d.address,d.port,
d.username,d.password);pools[c].onJob.addListener(jobHandler);pools[c].onError.addListener(errorHandler);pools[c].connect()}}if(void 0!==a.param)for(paramSetting=a.param,c=$jscomp.makeIterator(avalons),d=c.next();!d.done;d=c.next())d=d.value,void 0!==d&&(d.setVoltage(paramSetting.voltSet),d.setFrequency(paramSetting.freqSet));chrome.storage.local.set({pool:poolSetting,param:paramSetting})}},prelude=function(){chrome.runtime.sendMessage({type:"setting",pool:poolSetting,param:paramSetting});scanDevices();
chrome.hid.onDeviceAdded.addListener(hidAddedHandler);chrome.hid.onDeviceRemoved.addListener(hidRemovedHandler)},hidAddedHandler=function(a){var b=a.deviceId;avalons[b]=new Avalon(a,workQueue,paramSetting.voltSet,paramSetting.freqSet);chrome.runtime.sendMessage({type:"device",deviceId:b,deviceType:avalons[b].deviceType});avalons[b].onDetect.addListener(detectHandler);avalons[b].onNonce.addListener(nonceHandler);avalons[b].onStatus.addListener(statusHandler);hashrates[b]=hashrates[b]||Array.apply(null,
Array(721)).map(Number.prototype.valueOf,0);errors[b]=errors[b]||{error:0,all:0};enabled&&avalons[b].connect()},hidRemovedHandler=function(a){for(var b in avalons){var c=avalons[b];if(c.deviceId===a){c.stop();delete avalons[b];delete hashrates[b];delete errors[b];chrome.runtime.sendMessage({type:"delete",deviceId:a});break}}},main=function(){enabled=!0;activePool=Infinity;for(var a=0;a<poolSetting.length;a++){var b=poolSetting[a];pools[a]=new Pool(a,b.address,b.port,b.username,b.password)}thread.onmessage=
function(a){workQueue.push(a.data)};chrome.sockets.tcp.onReceive.addListener(tcpHandler);chrome.sockets.tcp.onReceiveError.addListener(tcpErrorHandler);a=$jscomp.makeIterator(pools);for(b=a.next();!b.done;b=a.next())b=b.value,b.onJob.addListener(jobHandler),b.onError.addListener(errorHandler),b.connect();calcHashrate();a=$jscomp.makeIterator(avalons);for(b=a.next();!b.done;b=a.next())b=b.value,void 0!==b&&b.connect()},tcpHandler=function(a){for(var b=$jscomp.makeIterator(pools),c=b.next();!c.done;c=
b.next())if(c=c.value,void 0!==c&&a.socketId===c.socketId){c.receive(a.data);break}},tcpErrorHandler=function(a){for(var b=$jscomp.makeIterator(pools),c=b.next();!c.done;c=b.next())c=c.value,void 0!==c&&a.socketId===c.socketId&&errorHandler(c.id)},jobHandler=function(a){var b=a.poolId,c=jobQueue[b];c.thisId=(c.thisId+1)%256;c.value[c.thisId]=a;if(b<activePool)3>activePool&&chrome.runtime.sendMessage({info:"Inactive",type:"pool",poolId:activePool}),activePool=b,workQueue.init(),chrome.runtime.sendMessage({info:"Active",
type:"pool",poolId:b});else{if(b>activePool){chrome.runtime.sendMessage({info:"Inactive",type:"pool",poolId:b});return}chrome.runtime.sendMessage({info:"Active",type:"pool",poolId:b});workQueue.init()}thread.postMessage({info:"newJob",job:a,jqId:c.thisId})},errorHandler=function(a){if(a===activePool){thread.postMessage({info:"clean"});for(var b=activePool+1;3>=b;b++)if(void 0===pools[b]){activePool=Infinity;thread.postMessage({info:"clean"});workQueue.init();break}else if(pools[b].alive){activePool=
b;thread.postMessage({info:"clean"});workQueue.init();var c=jobQueue[activePool];-1!==c.thisId&&thread.postMessage({info:"newJob",job:c.value[c.thisId],jqId:c.thisId})}}chrome.runtime.sendMessage({info:"Failed",type:"pool",poolId:a});setTimeout(function(){pools[a].connect()},5E3)},detectHandler=function(a){var b=a.deviceId;chrome.runtime.sendMessage({type:"status",deviceId:b,version:a.version,dna:a.dna});avalons[b].run()},nonceHandler=function(a){if(void 0!==jobQueue[a.poolId]){var b=jobQueue[a.poolId].value[a.jqId];
if(void 0!==b){var c=a.ntime+parseInt(b.ntime,16);errors[a.deviceId].all++;switch(utils.varifyWork(b,a.nonce2,c,a.nonce)){case 2:errors[a.deviceId].error++;break;case 0:pools[a.poolId].submit(b.jobId,utils.uInt2LeHex(a.nonce2,b.nonce2Size),c.toString(16),utils.uInt2LeHex(a.nonce,4));case 1:hashrates[a.deviceId][0]++,totalHashrate[0]++}}}},statusHandler=function(a){a.type="status";chrome.runtime.sendMessage(a)},scanDevices=function(){chrome.hid.getDevices(Avalon.FILTERS,function(a){if(!chrome.runtime.lastError){a=
$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next()){var b=b.value,c=b.deviceId;avalons[c]=new Avalon(b,workQueue,paramSetting.voltSet,paramSetting.freqSet);chrome.runtime.sendMessage({type:"device",deviceId:c,deviceType:avalons[c].deviceType});avalons[c].onDetect.addListener(detectHandler);avalons[c].onNonce.addListener(nonceHandler);avalons[c].onStatus.addListener(statusHandler);hashrates[c]=hashrates[c]||Array.apply(null,Array(721)).map(Number.prototype.valueOf,0);errors[c]=errors[c]||
{error:0,all:0}}}})},calcHashrate=function(){(function b(){var c=[],d,f,e;for(e in hashrates)d=hashrates[e],f=errors[e],void 0!==d&&(d.unshift(0),c.push({deviceId:e,hs1h:utils.arraySum(d.slice(1))/3600*4294967296,hs15m:utils.arraySum(d.slice(1,181))/900*4294967296,hs5m:utils.arraySum(d.slice(1,61))/300*4294967296,hs1m:utils.arraySum(d.slice(1,13))/60*4294967296,hs15s:utils.arraySum(d.slice(1,4))/15*4294967296,hs5s:d[1]/5*4294967296,errorRate:f.error/f.all}),d.pop());d=totalHashrate;d.unshift(0);c.push({deviceId:null,
hs1h:utils.arraySum(d.slice(1))/3600*4294967296,hs15m:utils.arraySum(d.slice(1,181))/900*4294967296,hs5m:utils.arraySum(d.slice(1,61))/300*4294967296,hs1m:utils.arraySum(d.slice(1,13))/60*4294967296,hs15s:utils.arraySum(d.slice(1,4))/15*4294967296,hs5s:d[1]/5*4294967296});d.pop();chrome.runtime.sendMessage({type:"hashrate",hashrate:c});enabled&&setTimeout(b,5E3)})()};
