var $jscomp={scope:{},global:this,initSymbolIterator:function(){Symbol=$jscomp.global.Symbol||{};Symbol.iterator||(Symbol.iterator="$jscomp$iterator");$jscomp.initSymbolIterator=function(){}},makeIterator:function(a){$jscomp.initSymbolIterator();if(a[Symbol.iterator])return a[Symbol.iterator]();if(!(a instanceof Array)&&"string"!=typeof a)throw Error();var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}},copyProperties:function(a,b){for(var c in b)a[c]=b[c]},inherits:function(a,
b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a}},hashrate=[0,0,0,0],enterFlag=!1,poolObj=[],nanoObj=[],renderChart=function(){Highcharts.setOptions({global:{useUTC:!1}});$("#container").highcharts({chart:{type:"spline",animation:Highcharts.svg,marginRight:10,events:{load:function(){var a=this.series;setInterval(function(){var b=(new Date).getTime(),c;for(c in a)a[c].addPoint([b,hashrate[c]],!0,!0)},2500)}}},title:{text:"Avalon miner Live Hashrate"},xAxis:{type:"datetime",
tickPixelInterval:150},yAxis:{title:{text:"Hash/s"},min:0,plotLines:[{value:0,width:1,color:"#808080"}]},tooltip:{formatter:function(){var a=Highcharts.dateFormat("%Y-%m-%d %H:%M:%S",this.x),a=a+"<table>",b;for(b in this.points)a+='<tr style="color: '+this.points[b].series.color+'"><td><b>'+this.points[b].series.name+"</b>:&nbsp;</td><td>"+numberShorten(this.points[b].y)+"Hs</td></tr>";return a+"</table>"},useHTML:!0,shared:!0},credits:{enabled:!1},legend:{enabled:!0,layout:"vertical",align:"right",
verticalAlign:"top",borderWidth:0},exporting:{enabled:!1},series:function(){for(var a=[],b=["5-Secondly","Minutely","Hourly","Pool"],c=["#808080","#feae1b","#00cc99","#0066FF"],d=[],f=(new Date).getTime(),e=-899;0>=e;e++)d.push({x:f+1E3*e,y:0});for(e in b)a.push({name:b[e],color:c[e],data:d});return a}()})},getPrice=function(){setInterval(function(){$.ajax({url:"https://data.btcchina.com/data/ticker?maket=all",success:function(a){$("#Price").html(a.ticker.last)}})},5E3)},getPoolHashRate=function(){setInterval(function(){var a=
$("#pool_info tr:eq(1)").data("id");if(void 0!==a){var b=$("#pool-address-"+a).html(),c=$("#pool-worker-"+a).html(),a=$("#pool-api-key-"+a).val();0<b.indexOf("btcchina")&&$.ajax({url:"https://pool.btcchina.com/api?api_key="+a,contentType:"application/json; charset=UTF-8",dataType:"json",success:function(a){a=a.user.workers;if(void 0!==a){a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())b=b.value,b.worker_name===c&&(hashrate[3]=b.hashrate)}}})}},5E3)},numberShorten=function(a){for(var b=
$jscomp.makeIterator([{prefix:"E",base:1E18},{prefix:"P",base:1E15},{prefix:"T",base:1E12},{prefix:"G",base:1E9},{prefix:"M",base:1E6},{prefix:"k",base:1E3}]),c=b.next();!c.done;c=b.next())if(c=c.value,a>c.base)return(a/c.base).toFixed(3)+" "+c.prefix;return a+" "},updateHashrate=function(a){a=a[a.length-1];hashrate[0]=a.hs5s;hashrate[1]=a.hs1m;hashrate[2]=a.hs1h},nanoList=function(a){nanoObj.push(a);console.log(nanoObj);enterFlag?deviceTr(a):($(".detect p img").attr("src","images/loading-m.gif"),
setTimeout(function(){detectDevice()},900))},detectFlag=!1,detectDevice=function(){if(!enterFlag&&(1>nanoObj.length&&($(".detect p").html('<img src="images/device.png">'),detectFlag=!1),!detectFlag&&1===nanoObj.length)){detectFlag=!0;$(".detect p img").remove();var a='<div style="text-align:center;"><button type="button" data-type="enter" class="btn btn-default"> Enter </button>  ';poolObj.length||(a+='  <button type="button" data-type="setting-pool" class="btn btn-default"> Setting pool </button>');
a+="</div>";$(".detect p").append(a);$("p").delegate("button","click",function(){enterFlag=!0;$(this).data("type");switch($(this).data("type")){case "enter":mainPage();break;case "setting-pool":settingPool()}})}},poolList=function(a){console.log(a);if(void 0!==a||null!==a)for(var b in a)void 0!==a[b]&&null!==a[b]&&poolObj.push(a[b])},loadingImg="<img id='loadImg' src='images/loading.gif'/>",guidePage=function(){var a=$("#main");a.addClass("center-img").append(loadingImg);setTimeout(function(){$("#loadImg").remove();
a.removeClass("center-img");var b='<div class="guide">\n\t\t\t<div class="logo">\n\t\t\t\t<img src="images/logo.png"/>\n\t\t\t</div>\n\t\t\t<div class="detect">\n\t\t\t\t<p>\n\t\t\t\t\t<img src="images/loading-m.gif"/>\n\t\t\t\t</p>\n\t\t\t\t<h4>To begin,plug your Avalon devices into the USB port of the computer</h4>\n\t\t\t\t<h5>if your Avalon devices are not recognized, please contact us by <a href="mailto:service@cannan-creative.com" target="_blank">service@cannan-creative.com</a></h5>\n\t\t\t</div>\n\t\t\t<p>'+
chrome.runtime.getManifest().name+" v"+chrome.runtime.getManifest().version+"</p>\n\t\t</div>";a.append(b);setTimeout(function(){$(".detect p img").attr("src","images/device.png")},500)},500)},mainPage=function(){enterFlag=!0;var a=$("#main");a.addClass("center-img").html(loadingImg);setTimeout(function(){$("#loadImg").remove();a.removeClass("center-img");var b=topPart(),b=b+chartPart(),b=b+tablePart();a.html(b);renderChart();bindPoolAdd();bindPoolButton();loopNano()},500);getPrice();getPoolHashRate()},
loopNano=function(){for(var a=$jscomp.makeIterator(nanoObj),b=a.next();!b.done;b=a.next())deviceTr(b.value)},bindPoolAdd=function(){$(".row-pool").delegate("button","click",function(){dialog({title:"Setting pool"});bindSaveButton()})},bindSaveButton=function(a){$(".form-group").delegate("button","click",function(){var b=$("#address").val(),c=$("#worker").val(),d=$("#apiKey").val();if(b.length&&c){0<=b.indexOf("://")&&(Pool_f=b.split("://"),b=Pool_f[1]);var f=b.split(":"),b=f[0],f=parseInt(f[1]||3333),
e=parseInt($("#poolId").val()),e=-1===e?void 0!==maxPoolId()?maxPoolId()+1:0:e;chrome.runtime.sendMessage({info:"NewPool",data:{url:b,port:f,username:c,poolId:e,apiKey:d}});"-1"==$("#poolId").val()?appendPool(e,{url:b,port:f,username:c,apiKey:d}):changePool(e,b+":"+f,c,d);hashrate[3]=0;$("#dialogModel").modal("hide");void 0!==a&&(poolObj.push({url:b,port:f,username:c,apiKey:d}),a())}else $("#message").html("Pool address or Worker is null").css("color","red")})},bindPoolButton=function(){$("td").delegate("button",
"click",function(){switch($(this).data("type")){case "edit":editPool($(this).data("id"));break;case "remove":removePool($(this).data("id"))}})},removePool=function(a){chrome.runtime.sendMessage({info:"DeletePool",data:{poolId:a}});$("#pool-tr-id-"+a).remove();1===$("#pool_info tr").size()&&$("#pool_info").append('<tr id="pool-null"><td colspan="4" align="center" style="color:#cfcfcf;">Setting pool</td></tr>')},removeNano=function(a){$("#nano-tr-id-"+a).remove();for(var b=[],c=$jscomp.makeIterator(nanoObj),
d=c.next();!d.done;d=c.next())d=d.value,d!==a&&b.push(d);nanoObj=b;enterFlag||detectDevice();1===$("#device tr").size()&&$("#device").append('<tr id="device-null"><td colspan="4" align="center" style="color:#cfcfcf;">Insert usb device</td></tr>')},editPool=function(a){a={address:$("#pool-address-"+a).html(),worker:$("#pool-worker-"+a).html(),apiKey:$("#pool-api-key-"+a).val(),poolId:a};dialog({title:"Update pool"},a);bindSaveButton()},changePool=function(a,b,c,d){$("#pool-address-"+a).html(b);$("#pool-worker-"+
a).html(c);$("#pool-api-key-"+a).val(d)},appendPool=function(a,b){void 0!==$("#pool-null").html()&&$("#pool-null").remove();$("#pool_info").append(poolTr(a,b));bindPoolButton()},maxPoolId=function(){return $("#pool_info tr:last-child").data("id")},topPart=function(){return'<div class="row top-div">\n\t\t<p><button class="button button-small">BTC Price : <span id="Price">------<span></button></p>\n        </div>'},chartPart=function(){return'<div id="container" style="min-width:300px;height:300px"></div>'},
panelPart=function(a,b,c){a="device"===a?devicePart():"pool"===a?poolPart():"";return tpl='<div class="col-xs-6 col-md-6 pull-'+b+'">\n\t\t<div class="panel panel-default">\n\t\t  <div class="panel-heading">\n\t\t    <h3 class="panel-title">'+c+'</h3>\n\t\t  </div>\n\t\t  <div class="panel-body">\n\t\t  '+a+"\n\t\t  </div>\n\t\t</div>\n\t</div>"},devicePart=function(a){a='<table class="table table-hover" id="device"><tr><th>Device</th>';a+="<th>ID</th>";a+="<th>Temp</th>";a+="<th>Frequency</th>";
a+="<th>Status</th>";a+="</tr>";return a+="</table>"},poolPart=function(){var a;a='<table class="table table-hover" id="pool_info"><tr><th>Address</th>';a+="<th>Worker</th>";a+="<th>Status</th>";a+="<th>Operation</th>";a+="</tr>";if(poolObj.length)for(var b in poolObj)void 0!==poolObj[b]&&null!==poolObj[b]&&(a+=poolTr(b,poolObj[b]));else a+='<tr id="pool-null"><td colspan="4" align="center" style="color:#cfcfcf;">Setting pool</td></tr>';a+="</table>";return a+='<div class="row row-pool"><button type="button" class="btn btn-default pull-right pool-add">Add Pool</button></div>'},
poolTr=function(a,b){var c;c=""+('<tr data-id="'+a+'" id="pool-tr-id-'+a+'" class="pool-tr-line">')+('<td id="pool-address-'+a+'">'+b.url+":"+b.port+"</td>");c+='<td id="pool-worker-'+a+'">'+b.username+"</td>";c+="<td>Normal</td>";c+='<td class="op">';c+=' <button class="btn btn-default btn-xs" data-id="'+a+'" data-type="edit">Edit</button>';c+=' <button class="btn btn-default btn-xs" data-id="'+a+'" data-type="remove">Remove</button>';c+="</td>";c+='<input type="hidden" id="pool-api-key-'+a+'" value="'+
b.apiKey+'"/>';return c+="</tr>"},deviceTr=function(a){void 0!==$("#device-null").html()&&$("#device-null").remove();var b=a.nanoId;a=a.deviceType;a=""+('<tr class="active" id="nano-tr-id-'+b+'">')+("<td>"+a+"</td>");a+='<td id="nano-device-id-'+b+'">'+b+"</td>";a+="<td>null</td>";a+='<td id="nano-frequency-'+b+'">0</td>';a+='<td id="nano-status-'+b+'">Normal</td>';a+="</tr>";$("#device").append(a)},tablePart=function(){var a;a='<div class="row">'+panelPart("device","left","Device List");a+=panelPart("pool",
"right","Pool List");return a+"</div>"},settingPool=function(){dialog({title:"Setting pool"});bindSaveButton(mainPage)},updateNanoData=function(a,b,c){switch(b){case "status":!0!==c?($("#nano-tr-id-"+a).removeClass("active").addClass("warning"),$("#nano-status-"+a).html("Connect failt")):$("#nano-status-"+a).html("Connect success");break;case "frequency":$("#nano-frequency-"+a).html(c)}},dialog=function(a,b){0<$("#dialogModel").length&&($("#dialogModel").remove(),$(".modal-backdrop").remove());var c,
d,f;c=a&&a.title?a.title:"Message";d=a&&a.fade?"fade":"";f='<div>\n\t\t<div class="form-group">\n\t\t<label for="Pool address">Pool address</label>\n\t\t<input type="text" class="form-control" id="address" placeholder="Pool address" value="'+(b&&b.address?b.address:"")+'">\n\t\t</div>\n\t\t<div class="form-group">\n\t\t<label for="Pool address">Worker</label>\n\t\t<input type="text" class="form-control" id="worker" placeholder="worker" value="'+(b&&b.worker?b.worker:"")+'">\n\t\t</div>\n\t\t<div class="form-group">\n\t\t<label for="apiKey">apiKey</label>\n\t\t<input type="text" class="form-control" id="apiKey" placeholder="apiKey" value="'+
(b&&b.apiKey?b.apiKey:"")+'">\n\t\t</div>\n\t\t<div class="form-group">\n\t\t<input type="hidden" id="poolId" value="'+(void 0===b||void 0===b.poolId?"-1":b.poolId)+'" />\n\t\t<button type="button" class="btn btn-default" id="add-pool-save"> Save </button>\n\t\t<span id="message"></span>\n\t\t</div>\n\t</div>';d='<div class="modal '+d+'" id="dialogModel"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>';
d+='<h4 class="modal-title"><strong>'+c+"</strong></h4></div>";d+='<div class="modal-body">'+f+"</div>";d+='<div class="modal-footer"></div>';d+="</div></div></div>";$("body").append(d);$("#dialogModel").modal({backdrop:"static",keyboard:!1})};
$(function(){guidePage();chrome.runtime.sendMessage({info:"Ready"});chrome.runtime.onMessage.addListener(function(a,b){if(-1<b.url.indexOf("background"))switch(a.info){case "PoolInit":console.log("PoolInit");poolList(a.setting);break;case "NewNano":console.log("NewNano");nanoList({nanoId:a.nanoId,deviceType:a.deviceType});console.log(a);break;case "NanoDeleted":console.log("NanoDeleted");removeNano(a.nanoId);break;case "NanoConnected":console.log("NanoConnected");updateNanoData(a.nanoId,"status",
a.success);break;case "NanoDetected":console.log("NanoDetected");break;case "NewStatus":console.log("NewStatus");console.log(a);updateNanoData(a.nanoId,"frequency",a.stat.frequency);break;case "PoolSubscribed":console.log("PoolSubscribed");break;case "PoolAuthorized":console.log("PoolAuthorized");break;case "Hashrate":updateHashrate(a.hashrate)}})});
